[project]
name = 'Tokenized-Life-Coaching-Quantum-Life-Purpose-Discovery'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.coach-verification]
path = 'contracts/coach-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.discovery-protocol]
path = 'contracts/discovery-protocol.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
